package Interfaz;

/**
 *
 * @author tonyl
 */
public class Limpieza extends javax.swing.JFrame {

    /**
     * Creates new form Habitaciones
     */
    public Limpieza() {
        initComponents();
        setLocationRelativeTo(null);
        cargarTablaLimpieza();
        jTextFDescripcionProblema.setEditable(false);
        this.setResizable(false);
        agregarBotonConsumo();
    }

    /**
     * Agrega (por código, fuera del GEN-code) una barra de menú con la opción
     * para registrar los insumos de LIMPIEZA usados en una habitación. Una barra
     * de menú se coloca sobre el contenido sin interferir con el GroupLayout del
     * formulario. Cada registro descuenta stock real del inventario.
     */
    private void agregarBotonConsumo() {
        javax.swing.JMenuBar barraMenu = new javax.swing.JMenuBar();
        javax.swing.JMenu menu = new javax.swing.JMenu("Inventario");
        javax.swing.JMenuItem item = new javax.swing.JMenuItem("Registrar insumos usados...");
        item.setToolTipText("Descontar del inventario los productos de limpieza usados en la habitación");
        item.addActionListener(e -> {
            String ref = jTextFNroHabitacion.getText().trim();
            DialogoConsumoInsumos d = new DialogoConsumoInsumos(
                    this, "LIMPIEZA", "Limpieza", "Nro Habitación", "Personal de Limpieza");
            d.setTipoFiltro("Limpieza");
            if (!ref.isEmpty()) {
                d.prellenarReferencia(ref);
            }
            d.setVisible(true);
        });
        menu.add(item);
        barraMenu.add(menu);
        setJMenuBar(barraMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFNroHabitacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFDescripcionProblema = new javax.swing.JTextField();
        jButtonActuzalizarProblema = new javax.swing.JButton();
        jButtonBuscarHabitacion = new javax.swing.JButton();
        jButtonSinProblema = new javax.swing.JButton();
        jButtonRegistrarProblema = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableContenido = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" REPORTE DE PROBLEMAS DE HABITACIÓN");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("PERSONAL DE LIMPIEZA");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nro Habitación: ");

        jTextFNroHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFNroHabitacionActionPerformed(evt);
            }
        });
        jTextFNroHabitacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFNroHabitacionKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("REGISTRO DE REPORTES :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Descripción del problema");

        jTextFDescripcionProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFDescripcionProblemaActionPerformed(evt);
            }
        });

        jButtonActuzalizarProblema.setBackground(new java.awt.Color(204, 204, 204));
        jButtonActuzalizarProblema.setText("Actualizar problema");
        jButtonActuzalizarProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActuzalizarProblemaActionPerformed(evt);
            }
        });

        jButtonBuscarHabitacion.setBackground(new java.awt.Color(204, 204, 204));
        jButtonBuscarHabitacion.setText("Buscar Habitación");
        jButtonBuscarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarHabitacionActionPerformed(evt);
            }
        });

        jButtonSinProblema.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSinProblema.setText("Sin problemas ");
        jButtonSinProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinProblemaActionPerformed(evt);
            }
        });

        jButtonRegistrarProblema.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRegistrarProblema.setText("Registrar problema ");
        jButtonRegistrarProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarProblemaActionPerformed(evt);
            }
        });

        jTableContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Habitación", "Descripción", "Estado", "Encargado"
            }
        ));
        jScrollPane2.setViewportView(jTableContenido);
        if (jTableContenido.getColumnModel().getColumnCount() > 0) {
            jTableContenido.getColumnModel().getColumn(0).setHeaderValue("Habitación");
            jTableContenido.getColumnModel().getColumn(1).setHeaderValue("Descripción");
            jTableContenido.getColumnModel().getColumn(2).setHeaderValue("Estado");
            jTableContenido.getColumnModel().getColumn(3).setHeaderValue("Acción");
        }

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonBuscarHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jButtonActuzalizarProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFNroHabitacion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFDescripcionProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonSinProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonRegistrarProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(361, 361, 361))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(157, 157, 157))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFDescripcionProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFNroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscarHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegistrarProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonActuzalizarProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSinProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFDescripcionProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFDescripcionProblemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFDescripcionProblemaActionPerformed

    private void jButtonBuscarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarHabitacionActionPerformed
        String numero = jTextFNroHabitacion.getText().trim();
        if (numero.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el número de la habitación a buscar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Entidades.Habitacion hab = controlador.SistemaHotel.getInstancia().getHotel().buscarHabitacionporNumero(numero);

        if (hab == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "La habitación " + numero + " no existe.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Bloqueamos la edición hasta que le den a "Actualizar problema"
        jTextFDescripcionProblema.setEditable(false);
        jTextFDescripcionProblema.setText(hab.getDescripcionProblema());

        String estadoStr = (hab.getEstado() == 'O') ? "Ocupada" : (hab.getEstado() == 'D') ? "Disponible" : "Mantenimiento";
        javax.swing.JOptionPane.showMessageDialog(this, "Habitación encontrada.\nEstado actual: " + estadoStr, "Búsqueda Exitosa", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonBuscarHabitacionActionPerformed

    private void jButtonRegistrarProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarProblemaActionPerformed
        String numero = jTextFNroHabitacion.getText().trim();
        String problema = jTextFDescripcionProblema.getText().trim();

        if (numero.isEmpty() || problema.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Busque una habitación y escriba la descripción del problema.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Entidades.Habitacion hab = controlador.SistemaHotel.getInstancia().getHotel().buscarHabitacionporNumero(numero);

        if (hab != null) {
            // Guardamos el problema y el encargado
            hab.setDescripcionProblema(problema);
            hab.setEncargadoLimpieza("Empleado Turno"); // Nota: Esto se cambiará automáticamente por el nombre cuando hagamos el Login

            // Lógica para proteger las habitaciones ocupadas
            if (hab.getEstado() == 'O') {
                javax.swing.JOptionPane.showMessageDialog(this, "Problema registrado.\nNOTA: La habitación está OCUPADA, por lo que su estado no se cambiará a Mantenimiento.", "Aviso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                hab.setEstado('M'); // Pasa a mantenimiento porque estaba libre
                javax.swing.JOptionPane.showMessageDialog(this, "Problema registrado. La habitación pasó a Mantenimiento.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

            // ¡Guardar en el archivo .dat!
            controlador.SistemaHotel.getInstancia().guardarCambios();

            // Refrescar tabla visual y limpiar formulario
            cargarTablaLimpieza();
            jTextFNroHabitacion.setText("");
            jTextFDescripcionProblema.setText("");
            jTextFDescripcionProblema.setEditable(false);
        }
    }//GEN-LAST:event_jButtonRegistrarProblemaActionPerformed

    private void jButtonSinProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinProblemaActionPerformed
        String numero = jTextFNroHabitacion.getText().trim();

        if (numero.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero busque la habitación que desea marcar como 'Sin problemas'.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Entidades.Habitacion hab = controlador.SistemaHotel.getInstancia().getHotel().buscarHabitacionporNumero(numero);

        if (hab != null) {
            // Borramos el registro del problema
            hab.setDescripcionProblema("");
            hab.setEncargadoLimpieza("");

            // Si estaba en Mantenimiento, la regresamos a Disponible. Si estaba Ocupada, se queda Ocupada.
            if (hab.getEstado() == 'M') {
                hab.setEstado('D');
            }

            // Persistencia
            controlador.SistemaHotel.getInstancia().guardarCambios();

            // Actualización visual
            cargarTablaLimpieza();
            javax.swing.JOptionPane.showMessageDialog(this, "Habitación " + numero + " marcada como SIN PROBLEMAS. Lista para usar.", "Limpieza Completa", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            jTextFNroHabitacion.setText("");
            jTextFDescripcionProblema.setText("");
            jTextFDescripcionProblema.setEditable(false);
        }
    }//GEN-LAST:event_jButtonSinProblemaActionPerformed

    private void jButtonActuzalizarProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActuzalizarProblemaActionPerformed
        if (jTextFNroHabitacion.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero busque una habitación.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Habilitamos la caja de texto para que puedan escribir o corregir el problema
        jTextFDescripcionProblema.setEditable(true);
        jTextFDescripcionProblema.requestFocus();
    }//GEN-LAST:event_jButtonActuzalizarProblemaActionPerformed

    private void jTextFNroHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFNroHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFNroHabitacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// 1. Preguntamos por seguridad
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea salir de esta pantalla?",
                "Confirmar Salida",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {

            // 2. Le preguntamos al sistema quién está conectado actualmente
            String rol = controlador.SistemaHotel.getInstancia().getHotel().getRolActual();

            // 3. Tomamos la decisión dinámica
            if (rol.equals("ADMIN")) {
                // Si es el administrador, lo devolvemos al menú principal
                new Menu_principal().setVisible(true);
            } else {
                // Si es un empleado normal (Chef, Limpieza, etc.), cerramos su sesión y se le manda al Login
                // También se limpia la memoria por seguridad
                controlador.SistemaHotel.getInstancia().getHotel().setRolActual("");
                new Login().setVisible(true);
            }

            // 4. Cerramos la ventana actual
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFNroHabitacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFNroHabitacionKeyTyped
        // 1. Capturamos el carácter exacto de la tecla presionada
        char c = evt.getKeyChar();

        // 2. Verificamos si NO es un número y NO es un punto
        if (!Character.isDigit(c) && c != '.') {
            evt.consume(); // ¡Destruye la pulsación! La letra no aparecerá en pantalla.
            return;
        }

        // 3. Evitar que el usuario escriba más de un punto decimal
        if (c == '.' && jTextFNroHabitacion.getText().contains(".")) {
            evt.consume(); // Destruye el segundo punto
        }

        //4. Bloque si hay mas de 4 digitos
        if (jTextFNroHabitacion.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFNroHabitacionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Limpieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Limpieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Limpieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Limpieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Limpieza().setVisible(true);
            }
        });
    }

    private void cargarTablaLimpieza() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTableContenido.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        java.util.List<Entidades.Habitacion> listaHabitaciones = controlador.SistemaHotel.getInstancia().getHotel().getListaHabitacion();

        if (listaHabitaciones != null) {
            for (Entidades.Habitacion hab : listaHabitaciones) {
                // Filtramos para que en la tabla solo salgan las habitaciones con reportes
                if (!hab.getDescripcionProblema().isEmpty() || hab.getEstado() == 'M') {

                    String estadoStr = (hab.getEstado() == 'D') ? "Disponible" : (hab.getEstado() == 'O') ? "Ocupada" : "Mantenimiento";
                    String encargado = hab.getEncargadoLimpieza().isEmpty() ? "Sin asignar" : hab.getEncargadoLimpieza();

                    Object[] fila = {
                        hab.getNumero(),
                        hab.getDescripcionProblema(),
                        estadoStr,
                        encargado
                    };
                    modelo.addRow(fila);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonActuzalizarProblema;
    private javax.swing.JButton jButtonBuscarHabitacion;
    private javax.swing.JButton jButtonRegistrarProblema;
    private javax.swing.JButton jButtonSinProblema;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableContenido;
    private javax.swing.JTextField jTextFDescripcionProblema;
    private javax.swing.JTextField jTextFNroHabitacion;
    // End of variables declaration//GEN-END:variables
}
