
package Interfaz;

import controlador.SistemaHotel;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jB1Iniciar = new javax.swing.JButton();
        jB1Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFContraseña = new javax.swing.JPasswordField();

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome :)");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TruGardenLogin.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(331, 440));

        jB1Iniciar.setBackground(new java.awt.Color(204, 204, 204));
        jB1Iniciar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jB1Iniciar.setText("Iniciar");
        jB1Iniciar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB1Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1IniciarActionPerformed(evt);
            }
        });

        jB1Salir.setBackground(new java.awt.Color(204, 204, 204));
        jB1Salir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jB1Salir.setText("Salir");
        jB1Salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB1Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1SalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("BIENVENIDO");

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel4.setText("Contraseña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordFContraseña)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFUsuario)))
                        .addGap(64, 64, 64))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jB1Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jB1Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordFContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB1Iniciar)
                    .addComponent(jB1Salir))
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
            .addComponent(jLabel2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB1SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1SalirActionPerformed
        // Salir del login:
        System.exit(WIDTH);
    SistemaHotel.getInstancia().cerrarConexion();
    }//GEN-LAST:event_jB1SalirActionPerformed

    private void jB1IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1IniciarActionPerformed
   // 1. Capturar los datos de los campos de texto
        String usuario = jTextFUsuario.getText().trim();
        // Usamos getPassword() porque es un JPasswordField
        String password = new String(jPasswordFContraseña.getPassword()).trim();

        if (usuario.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese su usuario y contraseña.", "Campos vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. VALIDACIÓN DEL SUPER ADMINISTRADOR (Por Defecto)
        if (usuario.equals("ADMIN") && password.equals("ADMIN123")) {
            
            //  Guardamos que entró el Admin en la "memoria" del sistema
            controlador.SistemaHotel.getInstancia().getHotel().setRolActual("ADMIN");
            
            javax.swing.JOptionPane.showMessageDialog(this, "Bienvenido al sistema, Administrador principal.", "Acceso Autorizado", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Redirige al Menú Principal (donde el admin tiene acceso a todo)
            new Menu_principal().setVisible(true);
            this.dispose(); // Cierra la ventana de Login
            return;
        }

        // 3. VALIDACIÓN DE EMPLEADOS
        // Traemos la lista de empleados guardados en el sistema
        java.util.List<Entidades.Empleado> listaEmpleados = controlador.SistemaHotel.getInstancia().getHotel().getListaEmpleados();
        Entidades.Empleado empleadoLogeado = null;

        if (listaEmpleados != null) {
            for (Entidades.Empleado emp : listaEmpleados) {
                // Comparamos que el DNI coincida tanto con el usuario como con la contraseña
                if (emp.getNumDocumento().equals(usuario) && emp.getNumDocumento().equals(password)) {
                    empleadoLogeado = emp;
                    break;
                }
            }
        }

        // Si no lo encontró, mostramos error
        if (empleadoLogeado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Credenciales incorrectas o el empleado no existe.", "Error de Acceso", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. REDIRECCIÓN SEGÚN EL ROL DEL EMPLEADO
        String rol = empleadoLogeado.getRol();
        
        //  Guardamos el rol y el empleado que acaba de entrar (sesión actual)
        controlador.SistemaHotel.getInstancia().getHotel().setRolActual(rol);
        controlador.SistemaHotel.getInstancia().getHotel().setEmpleadoActual(empleadoLogeado);

        javax.swing.JOptionPane.showMessageDialog(this, "Bienvenido, " + empleadoLogeado.getNombre() + ".\nRol: " + rol, "Acceso Autorizado", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Evaluamos el rol y abrimos la ventana correspondiente directamente
        if (rol.equalsIgnoreCase("Recepcionista")) {
            new Recepcionista().setVisible(true);

        } else if (rol.equalsIgnoreCase("Chef") || rol.equalsIgnoreCase("Cocinero")) {
            new Chef().setVisible(true);

        } else if (rol.equalsIgnoreCase("Limpieza") || rol.equalsIgnoreCase("Personal de Limpieza")) {
            new Limpieza().setVisible(true);

        } else if (rol.equalsIgnoreCase("Jefe de Almacen") || rol.equalsIgnoreCase("Almacen")) {
            new Gestion_almacen().setVisible(true);

        } else if (rol.equalsIgnoreCase("Jefe de Compras") || rol.equalsIgnoreCase("Compras")) {
            new Modulo_de_compras().setVisible(true);

        } else if (rol.equalsIgnoreCase("Gerente de RRHH") || rol.equalsIgnoreCase("Jefe de RRHH")
                || rol.equalsIgnoreCase("Recursos Humanos")) {
            // Nuevo rol: abre directamente el Módulo RRHH (F-017 a F-020)
            new Modulo_RRHH().setVisible(true);

        } else {
            // Si tiene un rol administrativo genérico (incluye Gerente General), lo mandamos al menú principal
            new Menu_principal().setVisible(true);
        }

        // Cerramos el login al final
        this.dispose();
    }//GEN-LAST:event_jB1IniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Login().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1Iniciar;
    private javax.swing.JButton jB1Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFContraseña;
    private javax.swing.JTextField jTextFUsuario;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
